config/routes.rb
Rails.application.routes.draw do
  root "main#index"

  get 'menu' => 'access#menu'
  get 'login' => 'access#new'
  delete 'logout' => 'access#destroy'
  resource :access, controller: 'access', only: [:new, :create, :destroy] do
    member do
      get :menu
    end
  end

  match 'about', to: "main#about", via: :get

  resources :categories do
    member do
      get :delete
    end
  end

  resources :tasks do
    member do
      get :delete
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :tasks, dependent: :nullify

  validates_length_of :name, within: 2..50

  scope :sorted, -> { order(:name) }

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_and_belongs_to_many :tasks

  validates :name, presence: true, uniqueness: true, length: {maximum: 20}

end

app/models/task.rb
class Task < ApplicationRecord

  attr_accessor :skip_titleize_name

  belongs_to :category, optional: true
  has_and_belongs_to_many :tags
  has_many :task_assignments
  has_many :users, through: :task_assignments

  validates_presence_of :name
  validates_length_of :name, maximum: 50
  validates_presence_of :position
  validates_numericality_of :position, greater_than: 0

  validate :description_has_no_prohibited_words

  before_validation :titleize_name, unless: :skip_titleize_name
  before_validation :set_default_position,
    if: Proc.new {|t| t.position.blank? || t.position < 1 }
  before_create :log_create
  before_update :log_update
  after_save :log_save
  after_commit :cleaning_reminder, if: :too_many_records?

  scope :complete, -> { where(completed: true) }
  scope :incomplete, -> { where(completed: false) }
  scope :sorted, -> { order(:position) }
  scope :search, -> (kw) { where("LOWER(name) LIKE ?", "%#{kw.downcase}%")}

  private

  def description_has_no_prohibited_words
    return unless description.present?
    prohibited_words = ['later', 'eventually', 'someday']
    prohibited_words.each do |word|
      if description.include?(word)
        errors.add(:description, "cannot contain prohibited word: #{word}")
      end
    end
  end

  def titleize_name
    self.name = name.titleize
  end

  def set_default_position
    max = Task.maximum(:position) || 0
    self.position = max + 1
  end

  def log_create
    logger.debug("Task being created: #{name}")
  end

  def log_update
    logger.debug("Task being updated: #{name}")
  end

  def log_save
    # runs on both create & update
    logger.debug("Task was saved: #{name}")
  end

  def cleaning_reminder
    # This could be a placeholder for sending an email to an admin
    logger.debug("Remember to prune old tasks")
  end

  def too_many_records?
    Task.count > 4
  end
end

app/models/task_assignment.rb
class TaskAssignment < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  has_many :task_assignments
  has_many :tasks, through: :task_assignments

  validates :first_name, presence: true, length: { maximum: 25 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :email, presence: true,
                    length: { maximum: 100 },
										uniqueness: true,
                    format: { with: EMAIL_REGEX },
                    confirmation: true

  validates_acceptance_of :terms

  scope :sorted, -> { order(:last_name, :first_name) }

  def full_name
    [first_name, last_name].join(' ')
  end

  def last_name_first
    [last_name, first_name].join(', ')
  end

  def abbrev_name
    first_initial = first_name.chars.first + ". "
    [first_initial, last_name].join(' ')
  end
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  skip_before_action :confirm_logged_in, only: [:new, :create]
  # before_action :get_user_info_from_session, only: [:menu, :new] PASO AL APPLICATION CONTROLLER ASI LO PUEDO USAR EN OTROS CONTROLLERS

  def menu
    # get_user_info_from_session LO SACO YA QUE LO TENGO EN EL BEFORE ACTION

    # Examples of render options:
    #
    # render('menu')
    #
    # render(plain: "Just render text.")
    #
    # render(html: "<strong>HTML text</strong>")
    #
    # render(json: Task.first)
    #
    # render(xml: ['dog', 'cat', 'mouse'])
    #
    # render(plain: 'OK', status: 200)
    #
    # path_to_404 = Rails.root.join('public', '404.html')
    # render(file: path_to_404)
    #
    # send_file(path_to_404)
    #
    # string = render_to_string(file: path_to_404)
    # logger.debug(string)
  end

  def new
    # get_user_info_from_session LO SACO YA QUE LO TENGO EN EL BEFORE ACTION
    if logged_in?
      redirect_to(menu_path)
    end
  end

  def create
    logger.info("*** Login User #{params[:username]}")

    cookies[:username] = params[:username]
    session[:user_id] = 1483

    flash[:notice] = 'Log in successful'
    redirect_to(menu_path)
  end

  def destroy
    logger.info("*** Logout User #{cookies[:username]}")

    cookies[:username] = nil
    session[:user_id] = nil

    flash[:notice] = 'Logged out'
    redirect_to(login_path)
  end

  # PASO AL APPLICATION CONTROLLER YA LO QUE LO USO EN DOS METODOS

  # private

  # def get_user_info_from_session
  #   @username =  cookies[:username]
  #   @user_id = session[:user_id]
  # end

  # def logged_in?
  #   session[:user_id].present?
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :get_user_info_from_session
  before_action :confirm_logged_in

  private

  def get_user_info_from_session
    @username =  cookies[:username]
    @user_id = session[:user_id]
  end

  def logged_in?
    session[:user_id].present?
  end

  def confirm_logged_in
    unless logged_in?
      flash[:notice] = 'Please log in'
      redirect_to(login_path)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.order(:name)
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to(categories_path)
    else
      render('new')
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to(categories_path)
    else
      render('edit')
    end
  end

  def delete
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to(categories_path)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def about
    @created_by = "Cristian"
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.order(:position)
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @count = Task.count
    @task = Task.new(position: @count + 1)
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      # The 'new' action is NOT being called here
      # Assign any instance variables needed
      # @count = Task.count
      render('new')
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render('edit')
    end
  end

  def delete
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(
      :name,
      :position,
      :completed,
      :description
    )
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/access/menu.html.erb
<% content_for(:title, 'Menu') %>

<div class="access index">
  <h1>Menu</h1>

<p> User: <%= @username %> (<%= @user_id %>) </p>
<%= button_to('Logout', logout_path, {method: :delete}) %>
  <ul>
    <li><%= link_to('Manage Tasks', tasks_path) %></li>
    <li><%= link_to('Manage Categories', categories_path) %></li>
    <li><%= link_to('About', {controller: 'main', action: 'about'}) %></li>
  </ul>

</div>

app/views/access/new.html.erb
<div class="access new">
  <h2>Welcome</h2>
  <p>A simulated log in form</p>

  <%= form_tag(access_path) do %>
    <table summary="login">
      <tr>
        <th><%= label_tag(:username) %></th>
        <td><%= text_field_tag(:username, params[:username]) %></td>
      </tr>
      <tr>
        <th><%= label_tag(:password) %></th>
        <td><%= password_field_tag(:password) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= submit_tag("Log In") %>
    </div>

  <% end %>
</div>

app/views/categories/_form.html.erb
<%= render(partial: 'layouts/error_messages', locals: {object: f.object}) %>

<table summary="Category form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
</table>

app/views/categories/delete.html.erb
<%= link_to("Back to List", categories_path, class: 'back-link') %>

<div class="categories delete">
  <h2>Delete Category</h2>

  <%= form_for(@category, method: 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this category?</p>
    <p><%= @category.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Category") %>
    </div>

  <% end %>
</div>

app/views/categories/edit.html.erb
<%= link_to("Back to List", categories_path, :class => 'back-link') %>

<div class="categories edit">
  <h2>Edit Category</h2>

  <%= form_for(@category) do |f| %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Edit Category") %>
    </div>

  <% end %>
</div>

app/views/categories/index.html.erb
<%= link_to('Back to Menu', menu_path, class: 'back-link') %><br />

<div class="categories index">
  <h2>Categories</h2>

  <%= link_to("Add New Category", new_category_path, class: 'action new') %>

  <table class="listing" summary="Category list" style="width: 100%;">
    <tr class="header">
      <th>Category</th>
      <th>Tasks</th>
      <th>Actions</th>
    </tr>
    <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.tasks.count %></td>
      <td class="actions">
        <%= link_to("Show", category_path(category), class: 'action show') %>
        <%= link_to("Edit", edit_category_path(category), class: 'action edit') %>
        <%= link_to("Delete", delete_category_path(category), class: 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/categories/new.html.erb
<%= link_to("Back to List", categories_path, :class => 'back-link') %>

<div class="categories new">
  <h2>Create Category</h2>

  <%= form_for(@category) do |f| %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Category") %>
    </div>

  <% end %>
</div>

app/views/categories/show.html.erb
<%= link_to("Back to List", categories_path, class: 'back-link') %>

<div class="categories show">
  <h2>Show Category</h2>

  <div class="actions">
    <%= link_to('Edit', edit_category_path(@category)) %>
    <%= link_to('Delete', delete_category_path(@category)) %>
  </div>

  <table summary="category detail view">
    <tr>
      <th>Name</th>
      <td><%= @category.name %></td>
    </tr>
    <tr>
      <th>Tasks</th>
      <td>
        <% @category.tasks.each do |task| %>
          <%= task.name %><br />
        <% end %>
      </td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @category.created_at.to_fs(:long) %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @category.updated_at.to_fs(:long) %></td>
    </tr>
  </table>

</div>

app/views/layouts/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="error-explanation">
		<h2><%= pluralize(object.errors.size, 'error') %> prohibited this record from being saved</h2>
		<p>There were problems with the following fields:</p>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice].present? %>
  <div id="flash-notice" style="border: 1px solid red; color: red; padding: 10px;">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task Manager<%= ' - ' + yield(:title) if content_for?(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield(:script) %>
  </head>

  <body>
    <header>
      <%= link_to(menu_path) do %>
        <%= image_tag('task_manager_logo.png', height: 25, alt: 'Task Manager Logo') %>
      <% end %>
      <% if session[:user_id].present? %>
        <span>
          User: <%= @username %> | <%= button_to('Logout', logout_path, {method: :delete}) %>
        </span>
      <% end %>
    </header>

    <div id="content">
      <%= render(partial: 'layouts/flash') %>
      <%= yield %>
    </div>

    <footer>
      Copyright <%= Time.now.year %>
    </footer>

  </body>
</html>

app/views/main/about.html.erb
<% content_for(:title, 'About') %>

<%= link_to('Back to Menu', menu_path, class: 'back-link') %><br />

<div class="main about">
  <h2>About</h2>

  <p>Description of the Task Manager.</p>

  <p>Created by <%= @created_by %></p>

</div>

<% content_for(:script) do %>
  <% name = "Kevin" %>
  <% # name = "Kevin'); alert('Gotcha" %>
  <%= javascript_tag("alert('Welcome, #{j(name)}!');") %>
<% end %>

app/views/main/index.html.erb
<h1>Task Manager</h1>
<p>This is an application for managing a to do list.</p>

<%= link_to('Categories', categories_path) %><br />
<%= link_to('Tasks', tasks_path(page: 1)) %><br />

<%= link_to('About', {action: 'about', page: 5, id: 20}) %><br />

app/views/tasks/_form.html.erb
<%= render(partial: 'layouts/error_messages', locals: {object: f.object}) %>

<table class="table table-bordered table-striped mt-4" summary="Task form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name, class: 'form-control') %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.text_field(:position, class: 'form-control') %></td>
  </tr>
  <tr>
    <th>Completed</th>
    <td><%= f.check_box(:completed, class: 'form-check-input') %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= f.text_area(:description, class: 'form-control') %></td>
  </tr>
</table>

app/views/tasks/delete.html.erb
<%= link_to("Back to List", tasks_path, class: 'btn btn-secondary mb-3') %>

<div class="tasks delete">
  <h2>Delete Task</h2>

  <%= form_for(@task, method: 'delete', html: {class: "mt-4"}) do |f| %>
    <% # url: task_path(@task), method: 'delete' %>

    <p class="mb-3">Are you sure you want to permanently delete this task?</p>
    <p class="mb-3"><%= @task.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Task", class: 'btn btn-danger') %>
    </div>

  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= link_to("Back to List", tasks_path, class: 'btn btn-secondary mb-3') %>

<div class="tasks edit">
  <h2>Edit Task</h2>

  <%= form_for(@task, html: {class: "mt-4"}) do |f| %>
    <% # url: task_path(@task), method: 'patch' %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons mt-4">
      <%= f.submit("Edit Task", class: 'btn btn-primary') %>
    </div>

  <% end %>
</div>

app/views/tasks/index.html.erb
<%= link_to('Back to Homepage', {controller: 'main', action: 'index'}, class: 'btn btn-secondary mb-3') %><br />

<div class="tasks index">
  <h2>Tasks</h2>

  <%= link_to("Add New Task", new_task_path, class: 'btn btn-primary mb-3') %>

  <table class="table table-striped table-bordered" summary="Task list" style="width: 100%;">
    <tr class="table-primary">
      <th>#</th>
      <th>Task</th>
      <th>Completed</th>
      <th>Description</th>
      <th>Category</th>
      <th>Actions</th>
    </tr>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.position %></td>
      <td><%= task.name %></td>
      <td><%= task.completed? ? 'Yes' : 'No' %></td>
      <td><%= truncate(task.description, length: 30 ) %></td>
      <td><%= task.category&.name || '-' %></td>
      <td class="actions">
        <%= link_to("Show", task_path(task), class: 'btn btn-info btn-sm me-2') %>
        <%= link_to("Edit", edit_task_path(task), class: 'btn btn-warning btn-sm me-2') %>
        <%= link_to("Delete", delete_task_path(task), class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' }) %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/tasks/new.html.erb
<%= link_to("Back to List", tasks_path, class: 'btn btn-secondary mb-3') %>

<div class="tasks new">
  <h2>Create Task</h2>

  <%= form_for(@task, html: {class: 'mt-4'}) do |f| %>
    <% # url: tasks_path, method: 'post' %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons mt-4">
      <%= f.submit("Create Task", class: 'btn btn-primary') %>
    </div>

  <% end %>
</div>

app/views/tasks/show.html.erb
<%= link_to("Back to List", tasks_path, class: 'btn btn-secondary mb-3') %>

<div class="tasks show">
  <h2>Show Task</h2>

  <div class="actions mb-3">
    <%= link_to('Edit', edit_task_path(@task), class: 'btn btn-warning me-2') %>
    <%= link_to('Delete', delete_task_path(@task), class: 'btn btn-danger') %>
  </div>

  <table class="table table-bordered" summary="Task detail view">
    <tr>
      <th>Name</th>
      <td><%= @task.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @task.position %></td>
    </tr>
    <tr>
      <th>Completed</th>
      <td><%= @task.completed? ? 'Yes' : 'No' %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= simple_format(word_wrap(@task.description, line_width: 120)) %></td>
    </tr>
    <tr>
      <th>Category</th>
      <td>
        <% if @task.category %>
          <%= @task.category.name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @task.created_at.to_s %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @task.updated_at.to_s %></td>
    </tr>
  </table>
</div>